name: Release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags: 
      - '*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: artixlinux/artixlinux:base-devel

    steps:
      - uses: actions/checkout@v4

      - name: Check permissions of GITHUB_WORKSPACE
        run: |
          whoami
          ls -la ..

      - name: Update build system
        run: pacman -Syu

      - name: Install artools-pkg
        run: pacman -Sy artools-pkg sudo

      - name: Build the package
        run: makepkg -Cs
