name: Release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags: 
      - '*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: 
      image: artixlinux/artixlinux:base-devel
      options: --privileged
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
    permissions:
      contents: write

    steps:
      - name: Update build system
        run: pacman -Syu --noconfirm

      - name: Install general build dependencies
        run: pacman -S git artools-pkg --noconfirm

      - name: "Allow the \"nobody\" user to run commands as root"
        run: "echo \"nobody ALL=(ALL:ALL) NOPASSWD: ALL\" >> /etc/sudoers"
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Add permissions to current directory for the \"nobody\" user"
        run: chown -R nobody:nobody .

      - name: Build the package
        run: sudo -u nobody makepkg -s --noconfirm

      - name: Import GPG key from secrets with passphrase
        run: echo "$GPG_SECRET" | gpg --batch --yes --import
      
      - name: Sign the package
        run: echo "$GPG_PASSPHRASE" | gpg --batch --yes --detach-sign --passphrase-fd 0 --pinentry-mode=loopback -u 'PatVax-artx-pkgbuilds <patvax0x0@gmail.com>' *.pkg.tar.zst

      - name: Install github cli
        run: pacman -S github-cli --noconfirm

      - name: Create the release
        run: sudo -E -u nobody gh release create --generate-notes --verify-tag -t "Release ${{ github.ref_name }}" ${{ github.ref_name }} *.pkg.tar.zst*